# Глобальная длина строки
line-length = 88

[lint]
# "F" (Pyflakes): Проверяет базовую логику. Ищет синтаксические ошибки, неиспользуемые переменные, потерянные импорты и опечатки.
# "E" (pycodestyle Errors): Ошибки оформления кода по стандарту PEP 8 (например, отсутствие пробелов вокруг = или слишком длинные строки).
# "W" (pycodestyle Warnings): Предупреждения по PEP 8 (менее критичные недочеты оформления, например, пустые строки).
# "UP" (pyupgrade): Помощник по современному синтаксису. Подсказывает, где можно переписать старый код на новый.
# "B" (flake8-bugbear): Ищет популярные "подводные камни" и неочевидные баги.
# "SIM" (flake8-simplify): Подсказывает, как сделать код проще и читабельнее (например, правило SIM105 про suppress).
# "I001" (isort): Следит за тем, чтобы импорты были отсортированы по алфавиту и разделены на логические блоки.
select = ["F", "E", "W", "UP", "B", "SIM", "I001"]
